name: hw-rankselect
version: '0.11.0.0'
synopsis: Rank-select
description: Please see README.md
category: Data, Conduit
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016 John Ky
license: BSD3
github: haskell-works/hw-rankselect
homepage: http://github.com/haskell-works/hw-rankselect#readme
extra-source-files:
- README.md
- data/README.md
dependencies:
- hw-rankselect-base >=0.2.0.0
- vector

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -O2
  - -msse4.2
  exposed-modules:
  - HaskellWorks.Data.RankSelect.CsPoppy
  - HaskellWorks.Data.RankSelect.CsPoppy.Internal
  - HaskellWorks.Data.RankSelect.Poppy512
  dependencies:
  - base >=4 && <5
  - deepseq
  - hw-balancedparens >=0.1.0.0
  - hw-bits >=0.6.0.0
  - hw-prim >=0.4.0.3

executables:
  hw-rankselect:
    main: Main.hs
    source-dirs: app
    default-extensions:
    - OverloadedStrings
    - TupleSections
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2
    - -msse4.2
    dependencies:
    - base >=4.7 && <5
    - directory
    - hw-bits >=0.4.0.0
    - hw-prim >=0.4.0.0
    - hw-rankselect
    - lens
    - mmap
    - mtl
    - optparse-applicative
    when:
    - condition: os(osx)
      cpp-options:
      - -D__attribute__(A)=
      - -D_Nullable=
      - -D_Nonnull=

tests:
  hw-rankselect-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base >=4 && <5
    - QuickCheck
    - directory
    - hedgehog
    - hspec
    - hw-bits >=0.4.0.0
    - hw-hedgehog
    - hw-hedgehog >=0.1.0.1
    - hw-hspec-hedgehog
    - hw-hspec-hedgehog
    - hw-prim >=0.4.0.0
    - hw-rankselect
    - mmap

benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
    - -O2
    - -Wall
    - -msse4.2
    dependencies:
    - base >=4 && <5
    - bytestring
    - conduit
    - criterion
    - directory
    - hw-bits >=0.4.0.0
    - hw-prim >=0.4.0.0
    - hw-rankselect
    - mmap
    - resourcet

when:
- condition: (flag(bmi2)) && (impl(ghc >=8.4.1))
  ghc-options:
  - -mbmi2
  - -msse4.2
  cpp-options:
  - -DBMI2_ENABLED

flags:
  bmi2:
    description: Enable bmi2 instruction set
    manual: false
    default: false
