#!/usr/bin/env bash

filter="$1"

shift

do_poll() {
  for i in {1..120}; do
    echo -n "Polling "
    for j in {1..5}; do
      sleep 12
      echo -n .
      (ps aux | grep "$filter" > /dev/null) || exit 1
    done
    echo ""
  done
}

do_poll & "$@"
